Traceback (most recent call last):
  File "/home/ninja/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/ninja/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ninja/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/ninja/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/ninja/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ninja/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/home/ninja/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/ninja/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
env = gym.make('FrozenLake-v0')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m~/anaconda3/lib/python3.8/site-packages/gym/envs/registration.py[0m in [0;36mspec[0;34m(self, path)[0m
[1;32m    157[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 158[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0menv_specs[0m[0;34m[[0m[0mid[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    159[0m         [0;32mexcept[0m [0mKeyError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyError[0m: 'FrozenLake-v0'

During handling of the above exception, another exception occurred:

[0;31mDeprecatedEnv[0m                             Traceback (most recent call last)
[0;32m/tmp/ipykernel_8446/582203357.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0menv[0m [0;34m=[0m [0mgym[0m[0;34m.[0m[0mmake[0m[0;34m([0m[0;34m'FrozenLake-v0'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/anaconda3/lib/python3.8/site-packages/gym/envs/registration.py[0m in [0;36mmake[0;34m(id, **kwargs)[0m
[1;32m    233[0m [0;34m[0m[0m
[1;32m    234[0m [0;32mdef[0m [0mmake[0m[0;34m([0m[0mid[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 235[0;31m     [0;32mreturn[0m [0mregistry[0m[0;34m.[0m[0mmake[0m[0;34m([0m[0mid[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    236[0m [0;34m[0m[0m
[1;32m    237[0m [0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.8/site-packages/gym/envs/registration.py[0m in [0;36mmake[0;34m(self, path, **kwargs)[0m
[1;32m    126[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    127[0m             [0mlogger[0m[0;34m.[0m[0minfo[0m[0;34m([0m[0;34m"Making new env: %s"[0m[0;34m,[0m [0mpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 128[0;31m         [0mspec[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mspec[0m[0;34m([0m[0mpath[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    129[0m         [0menv[0m [0;34m=[0m [0mspec[0m[0;34m.[0m[0mmake[0m[0;34m([0m[0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    130[0m         [0;32mreturn[0m [0menv[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.8/site-packages/gym/envs/registration.py[0m in [0;36mspec[0;34m(self, path)[0m
[1;32m    183[0m             ]
[1;32m    184[0m             [0;32mif[0m [0mmatching_envs[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 185[0;31m                 raise error.DeprecatedEnv(
[0m[1;32m    186[0m                     "Env {} not found (valid versions include {})".format(
[1;32m    187[0m                         [0mid[0m[0;34m,[0m [0mmatching_envs[0m[0;34m[0m[0;34m[0m[0m

[0;31mDeprecatedEnv[0m: Env FrozenLake-v0 not found (valid versions include ['FrozenLake-v1'])
DeprecatedEnv: Env FrozenLake-v0 not found (valid versions include ['FrozenLake-v1'])

