Traceback (most recent call last):
  File "/home/ninja/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 626, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/home/ninja/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 96, in ensure_async
    result = await obj
  File "/home/ninja/anaconda3/lib/python3.8/site-packages/jupyter_client/channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ninja/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/ninja/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ninja/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/ninja/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/ninja/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ninja/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/home/ninja/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 838, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/home/ninja/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 650, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/home/ninja/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 697, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['runs = 50', 'print("Exp 1: entropia")', 'exp_1 = run_experiment(strategy="entropy",runs=runs,df=df,show=True)', 'print("Exp 2: ignorância")', 'exp_2 = run_experiment(strategy="ignorance",runs=runs,df=df,show=True)']
...
['exp_4 = run_experiment(strategy="random",runs=runs,df=df,show=True)', 'print("Exp 5: ignorância modificada")', 'exp_5 = run_modified_experiment(strategy="priorisation",runs=runs,df=df,show=True)', 'print("Exp 6: entropia + ignorância modificada")', 'exp_6 = run_modified_experiment(strategy="ignorance",runs=runs,df=df,show=True)']
-------------------

